# Generated by Django 4.1.7 on 2023-04-12 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Angelaapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='Student',
        ),
    ]
