# Generated by Django 4.1.7 on 2023-04-14 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Angelaapp', '0002_alter_student_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('Position', models.CharField(max_length=50)),
                ('office', models.CharField(max_length=50)),
                ('Age', models.IntegerField()),
                ('Start_date', models.DateField()),
                ('Salary', models.IntegerField()),
            ],
        ),
    ]
