# Generated by Django 4.1.7 on 2023-04-14 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Angelaapp', '0004_post_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Text',
            field=models.TextField(max_length=50),
        ),
    ]
