# Generated by Django 4.1.7 on 2023-04-14 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Angelaapp', '0006_alter_post_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Text',
            field=models.CharField(max_length=50),
        ),
    ]
