# Generated by Django 4.1.7 on 2023-04-17 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Angelaapp', '0007_alter_post_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Text',
        ),
    ]
